//资源数据(左侧菜单栏)
const menus=[
    {
        name:'用户管理',
        childMenu:[
            {
                name:'用户管理',
                path:'/user'
            },
            {
                name:'学生管理',
                path:'/student'
            },
            {
                name:'教师管理',
                path:'/teacher'
            },
            {
                name:'资源管理',
                path:'/menu'
            },
            {
                name:'角色管理',
                path:'/role'
            },
            {
                name:'直播管理',
                path:'/video'
            }
        ]
    },
    {
        name:'教学管理',
        childMenu:[
            {
                name:'课程管理',
                path:'/course'
            },
            {
                name:'班级管理',
                path:'/clazz'
            }
        ]
    },
    {
        name:'设备管理',
        childMenu:[
	{
                    name:'传感器列表',
                    path:'/sensorlist'
                },
                {
                    name:'控制器列表',
                    path:'/controllerlist'
                },
                {
                    name:'设备监控',
                    path:'/device'
                }
        ]
    },
    {
        name:'考勤管理',
        childMenu:[
            {
                name:'课程考勤记录',
                path:'/attendance'
            },
            {
                name:'个人考勤记录',
                path:'/attendance2'
            }
        ]
    }
];
export default menus;